import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./components/provider";
import Header from "./components/Header";
import Footer from "./components/Footer";
import ClippedDrawer from "./components/SideMenu";
import { Grid } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
     
        <Provider>
          <>
         
          {children}
          <Footer/>
          </>
        </Provider>
      </body>
    </html>
  );
}
